---
- hosts: all
  become: true

  pre_tasks:
    - name: Update apt-get cache if needed
      apt: 
        update_cache: yes 
        cache_valid_time: 3600

  handlers:
    - name: restart nginx
      service: name=nginx state=restarted
  

- hosts: loadbalancer
  become: true
  tasks:
    - name: Download Nginx signing key
      get_url:
        url: http://nginx.org/keys/nginx_signing.key
        dest: /home/vagrant
    
    - name: Add key in apt-get repo
      command: apt-key add nginx_signing.key

    - name: Add nginx to package
      copy:
        src: ./sources.list
        dest: /etc/apt/sources.list

    - name: Update apt-get repo
      apt: 
        update_cache: yes
    
    - name: Install nginx web server
      apt:
        state: present
        name: nginx
    
    - name: Start nginx
      service: name=nginx state=started
    
    - name: Check if file already exist
      stat: 
        path: /etc/nginx/conf.d/default.conf
      register: file_stats

    - name: Rename default nginx conf file
      command: mv /etc/nginx/conf.d/default.conf /etc/nginx/conf.d/default.conf.bak
      when: file_stats.stat.exists
    
    - name: Copy nginx server file
      copy:
        src: ./server.conf
        dest: /etc/nginx/conf.d/server.conf
   
    - name: Copy nginx http file
      copy:
        src: ./nginx.conf
        dest: /etc/nginx/nginx.conf

    - name: Create webserver root dir 
      become: false
      file:
        path: /home/vagrant/public_html
        state: directory
        owner: vagrant

    - name: Copy index file
      become: false
      copy:
        src: ./index.html
        dest: /home/vagrant/public_html/index.html

    - name: Restart nginx
      service: 
        name: nginx
        state: restarted
      
- hosts: backends
  become: true
  tasks:
    - name: "Get software for apt repository management."
      apt:
        state: present
        name:
          - python-apt
          - python-pycurl

    - name: Add ondrej repository for later versions of PHP.
      apt_repository: repo='ppa:ondrej/php' update_cache=yes

    - name: "Install Apache, PHP, and other dependencies."
      apt:
        state: present
        name:
          - git
          - curl
          - unzip
          - sendmail
          - apache2
          - php7.1-common
          - php7.1-cli
          - php7.1-dev
          - php7.1-gd
          - php7.1-curl
          - php7.1-json
          - php7.1-opcache
          - php7.1-xml
          - php7.1-mbstring
          - php7.1-pdo
          - php7.1-mysql
          - php-mysql
          - php-apcu
          - libpcre3-dev
          - libapache2-mod-php7.1

    - name: Disable the firewall (since this is for local dev only).
      service: name=ufw state=stopped 

    - name: Start apache
      service: name=apache2 state=started
        
    - name: Copy text into index page
      become_user: root
      shell: echo "This is the backend of {{ inventory_hostname }}" > /var/www/html/index.html
    
    - name: Copy DB connection test file
      copy:
        src: ./connect.php
        dest: /var/www/html/connect.php

- hosts: database
  become: true
  tasks:
    - name: "Install Python dependencies"
      apt:
        state: present
        name:
          - python-apt
          - python-pycurl

    - name: Add ondrej repository for later versions of PHP.
      apt_repository: repo='ppa:ondrej/php' update_cache=yes

    